apiVersion: v1
kind: Pod
metadata:
  name: ceph-connector-secure
  namespace: lab-configmap-secret
spec:
  containers:
  - name: ceph-app
    image: python:3.9
    command: ["sleep", "1000"]
    volumeMounts:
    - name: ceph-creds
      mountPath: /etc/ceph-credentials
      readOnly: true
  volumes:
  - name: ceph-creds
    secret:
      secretName: ceph-s3-credentials
      defaultMode: 0600
