apiVersion: v1
kind: Pod
metadata:
  name: spark-config-reader
  namespace: lab-configmap-secret
spec:
  containers:
  - name: spark
    image: apache/spark:latest
    command: ["sleep", "600"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: data-platform-config
